#!/bin/bash

# author: Cleiton Ramos dos Santos <sit_cramos@uolinc.com> atual <cleramos@uolinc.com>
# describe: Prepara o equipamento para o Homolog.sh.x
# version: 0.8
# licence: MIT License

#Alterando Sources
cd /etc/apt/
mv sources.list sources.list.bkp

#Criando novo sources.list com server BR
echo "deb http://mirror.ufam.edu.br/ubuntu/ focal main restricted" >> sources.list
echo "deb http://mirror.ufam.edu.br/ubuntu/ focal-updates main restricted" >> sources.list
echo "deb http://mirror.ufam.edu.br/ubuntu/ focal universe" >> sources.list
echo "deb http://mirror.ufam.edu.br/ubuntu/ focal-updates universe" >> sources.list
echo "deb http://mirror.ufam.edu.br/ubuntu/ focal multiverse" >> sources.list
echo "deb http://mirror.ufam.edu.br/ubuntu/ focal-updates multiverse" >> sources.list
echo "deb http://mirror.ufam.edu.br/ubuntu/ focal-backports main restricted universe multiverse" >> sources.list
echo "deb http://mirror.ufam.edu.br/ubuntu/ focal-security main restricted" >> sources.list
echo "deb http://mirror.ufam.edu.br/ubuntu/ focal-security universe" >> sources.list
echo "deb http://mirror.ufam.edu.br/ubuntu/ focal-security multiverse" >> sources.list

#Repo Anydesk
echo "deb http://deb.anydesk.com/ all main" >> sources.list

#Adicionando permissão AnyDesk
wget -qO - https://keys.anydesk.com/repos/DEB-GPG-KEY | apt-key add -

#Tunando Conexao do Dell Latitude 5420 
echo on | sudo tee /sys/bus/pci/devices/0000\:00\:16.0/power/control

#Atualizando Repos e Atualizando Apps
apt-get update -y && apt-get upgrade -y

#Instalando AnyDesk
apt-get install anydesk -y

#Instalando libnss3 (serve para o PulseSecure)
apt-get install libnss3-tools -y

#Instalando Pulse
cd /home/mutley/Alice
chmod +x Pulse_Ubuntu_22.deb
dpkg -i Pulse_Ubuntu_22.deb

#Permissão ao Homolog.sh.x
chmod +x 22QAhomolog.sh.x

#Instalando o net-tools
apt-get install net-tools -y

#Copiando Homolog para Area de Trabalho
cp 22QAhomolog.sh.x /home/mutley/Desktop

#Deletando Alice
chmod 777 /home/mutley/Alice
rm -rf /home/mutley/Alice

zenity --info --text="22QAHOMOLOG ESTÁ NA /HOME/MUTLEY/DESKTOP"
